version: '3.9'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-latest
    ports:
      - 9000:9000
    volumes:
      - /etc/prometheus:/config
      - prometheus-data:/prometheus
    restart: unless-stoped
    command:
    - "--config.file=/config/prometheus.yml"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped